Chrome extension
cocos-creator/web-extension-detect-engine pull request #1
Opened 2017-12-23 02:10 UTC by cyy641278529

A chrome extension to detect facebook instant game engine information

2017-12-23 03:44 UTC, jareguo commented on js/contentscript.js
> +var script = document.createElement('script');
这个脚本会不会在所有网页中都激活？

2017-12-23 03:45 UTC, jareguo commented on README.md
> +Download and open chrome => More Tools => Extensions
不用叫别人 Download Chrome...

2017-12-23 03:46 UTC, jareguo commented on README.md
> +Download and open chrome => More Tools => Extensions
加上中文：More Tools（更多工具）Extensions（扩展程序）

2017-12-23 03:48 UTC, jareguo commented on README.md
> +=> Load unpacked extension => load this extension
这里好像少了一步，要先叫他们”开启开发者模式“，然后”加载已解压的扩展程序“
另外这个插件如何下载也没说清楚，最好是把下载地址写上：”https://github.com/cocos-creator/web-extension-detect-engine/archive/master.zip“

2017-12-25 02:22 UTC, cyy641278529 commented on js/contentscript.js
> +var script = document.createElement('script');
不会,因为在conten_script 里有设定了 matches ,满足 matches 才会触发 contentscript

2017-12-25 15:44 UTC, jareguo requested changes

2017-12-25 15:44 UTC, jareguo commented on js/contentscript.js
>  document.body.appendChild(script);
这里面既然都能操作 document 了，应该就能直接执行引擎判断代码了，不需要再通过 append script element 去执行

2017-12-25 15:47 UTC, jareguo commented on js/contentscript.js
> +script.innerText += "if(window.wwf){engine = 'wwf' + window.wwf.version};";
把这对的 if else 改成数据驱动的形式进行解析，并且把 CocosEngine 也作为一种普通的 engine 进行判断。
数据驱动的意思就是，定义一个数组，数组里声明了所有引擎的判断方式、引擎名称、版本获取方式。然后遍历这个数组依次判断是否满足指定的引擎。

2017-12-25 15:48 UTC, jareguo commented on manifest.json
> +  "description": "Get the facebook instant ganme Engine Edition",
ganme -> games,
Edition -> version

2017-12-26 07:49 UTC, jareguo commented on js/contentscript.js
> +    if (!engine_judge) { item.innerText += '其他引擎' };
这块代码还是太乱了，麻烦梳理下

2017-12-26 14:15 UTC, merged